// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBesd2EY_3g7Qo_avv2o4i66kO9W0u4U4E',
    appId: '1:252730768817:web:9c43f57407615b23ca1190',
    messagingSenderId: '252730768817',
    projectId: 'whatnot-store',
    authDomain: 'whatnot-store.firebaseapp.com',
    storageBucket: 'whatnot-store.firebasestorage.app',
    measurementId: 'G-7LBQRQRS3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLptd7VRPggT7rpHr-RJIKWKUhrr3yw7k',
    appId: '1:252730768817:android:a00ec20514f6b49aca1190',
    messagingSenderId: '252730768817',
    projectId: 'whatnot-store',
    storageBucket: 'whatnot-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfp4s_MLB1kmFiiIFNlxbaWi_AyJ0Zcpo',
    appId: '1:252730768817:ios:d092235c3ecc344cca1190',
    messagingSenderId: '252730768817',
    projectId: 'whatnot-store',
    storageBucket: 'whatnot-store.firebasestorage.app',
    iosBundleId: 'com.inizio.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfp4s_MLB1kmFiiIFNlxbaWi_AyJ0Zcpo',
    appId: '1:252730768817:ios:d092235c3ecc344cca1190',
    messagingSenderId: '252730768817',
    projectId: 'whatnot-store',
    storageBucket: 'whatnot-store.firebasestorage.app',
    iosBundleId: 'com.inizio.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBesd2EY_3g7Qo_avv2o4i66kO9W0u4U4E',
    appId: '1:252730768817:web:a5001548034c5c48ca1190',
    messagingSenderId: '252730768817',
    projectId: 'whatnot-store',
    authDomain: 'whatnot-store.firebaseapp.com',
    storageBucket: 'whatnot-store.firebasestorage.app',
    measurementId: 'G-8W95T55PCT',
  );
}
